import { Product } from "@/types/product";

export const sampleProducts: Omit<Product, "id">[] = [
  {
    name: "Premium Kitchen Knife Set",
    price: 129.99,
    category: "Kitchen Tools",
    image: "/products/knife-set.jpg",
    images: ["/products/knife-set.jpg", "/products/knife-set-2.jpg"],
    featured: true,
    tags: ["knives", "kitchen", "professional", "cooking", "new"],
  },
  {
    name: "Stainless Steel Cookware",
    price: 89.99,
    category: "Cookware",
    image: "/products/cookware.jpg",
    images: ["/products/cookware.jpg", "/products/cookware-2.jpg"],
    featured: false,
    tags: ["cookware", "stainless-steel", "pots", "pans", "sale"],
  },
  {
    name: "Digital Kitchen Scale",
    price: 39.99,
    category: "Kitchen Tools",
    image: "/products/scale.jpg",
    images: ["/products/scale.jpg", "/products/scale-2.jpg"],
    featured: false,
    tags: ["scale", "digital", "baking", "precision"],
  },
  {
    name: "Electric Mixer",
    price: 159.99,
    category: "Appliances",
    image: "/products/mixer.jpg",
    images: ["/products/mixer.jpg", "/products/mixer-2.jpg"],
    featured: false,
    tags: ["mixer", "baking", "appliance", "stand-mixer"],
  },
  {
    name: "Bamboo Cutting Board",
    price: 24.99,
    category: "Kitchen Tools",
    image: "/products/cutting-board.jpg",
    images: ["/products/cutting-board.jpg", "/products/cutting-board-2.jpg"],
    featured: false,
    tags: ["bamboo", "cutting-board", "eco-friendly", "sustainable"],
  },
  {
    name: "Coffee Maker",
    price: 199.99,
    category: "Appliances",
    image: "/products/coffee-maker.jpg",
    images: ["/products/coffee-maker.jpg", "/products/coffee-maker-2.jpg"],
    featured: false,
    tags: ["coffee", "appliance", "programmable", "thermal"],
  },
];
