[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

# Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Functions for API routes
[functions]
  directory = ".netlify/functions"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"

# Handle client-side routing for SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
# NEXT_PUBLIC_APP_VERSION = "1.0.0"
